# Generated by Django 4.2.6 on 2023-11-21 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cidade', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cidade')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Cidade')),
                ('estado', models.SmallIntegerField(verbose_name='Estado')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep_inicial', models.IntegerField(null=True, verbose_name='CEP Inicial')),
                ('cep_final', models.IntegerField(null=True, verbose_name='CEP Final')),
                ('estado_nome', models.CharField(max_length=50, verbose_name='Nome do Estado')),
                ('ddd', models.SmallIntegerField(null=True, verbose_name='DDD')),
            ],
            options={
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
                'db_table': 'cidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('fantasia', models.CharField(blank=True, default='', max_length=50, verbose_name='nome fantasia')),
                ('pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='pessoa')),
                ('codigo', models.CharField(blank=True, default='', max_length=10, verbose_name='código')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail')),
                ('instagram', models.CharField(blank=True, default='', max_length=50, verbose_name='instagram')),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=12, verbose_name='inscrição estadual')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='cnpj')),
                ('cpf', models.CharField(blank=True, default='', max_length=14, verbose_name='cpf')),
                ('chave', models.CharField(default='', editable=False, max_length=14, verbose_name='chave')),
                ('endereco_cep', models.CharField(blank=True, default='', max_length=10, verbose_name='cep')),
                ('endereco_uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='', max_length=2, verbose_name='uf')),
                ('endereco_cidade', models.CharField(blank=True, default='', max_length=50, verbose_name='cidade')),
                ('endereco_logradouro', models.CharField(blank=True, default='', max_length=100, verbose_name='logradouro')),
                ('endereco_bairro', models.CharField(blank=True, default='', max_length=50, verbose_name='bairro')),
                ('endereco_numero', models.CharField(blank=True, default='', max_length=20, verbose_name='número')),
                ('telefone_1', models.CharField(blank=True, default='', max_length=15, verbose_name='telefone 1')),
                ('telefone_2', models.CharField(blank=True, default='', max_length=15, verbose_name='telefone 2')),
                ('marcas', models.TextField(blank=True, default='', verbose_name='marcas')),
                ('credenciado', models.IntegerField(editable=False, verbose_name='credenciado')),
                ('cadastro', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='cadastro')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cpf', models.CharField(blank=True, default='', max_length=14, verbose_name='cpf')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=15, verbose_name='telefone 1')),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='VendedorMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.marca', verbose_name='marca')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.vendedor', verbose_name='vendedor')),
            ],
            options={
                'db_table': 'vendedor_marca',
            },
        ),
        migrations.CreateModel(
            name='ClienteMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente', verbose_name='cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.marca', verbose_name='marca')),
            ],
            options={
                'db_table': 'cliente_marca',
            },
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('chave',), name='cliente_chave_idx'),
        ),
    ]
