# Generated by Django 4.2.6 on 2023-11-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pessoa',
            field=models.CharField(choices=[('PF', 'PESSOA FÍSICA'), ('PJ', 'PESSOA JURÍDICA')], default='PJ', max_length=2, verbose_name='pessoa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_1',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='telefone fixo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_2',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='telefone móvel'),
        ),
    ]
