# Generated by Django 4.2.6 on 2024-01-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_alter_cliente_pessoa_alter_cliente_telefone_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vendedores',
            field=models.TextField(blank=True, default='', null=True, verbose_name='vendedores'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='credenciado',
            field=models.IntegerField(editable=False, null=True, verbose_name='credenciado'),
        ),
    ]
