# Generated by Django 4.2.6 on 2024-01-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_cliente_vendedores_vendedor_credenciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='credenciado',
            field=models.IntegerField(editable=False, null=True, verbose_name='credenciado'),
        ),
        migrations.AddField(
            model_name='marca',
            name='credenciado',
            field=models.IntegerField(editable=False, null=True, verbose_name='credenciado'),
        ),
    ]
