# Generated by Django 4.2.6 on 2024-01-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_grupo_credenciado_marca_credenciado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('tipo', models.SmallIntegerField(choices=[('COMPRADOR', 'COMPRADOR'), ('GERENTE', 'GERENTE'), ('SOCIO', 'SÓCIO/ADMINISTRADOR'), ('PROPRIETARIO', 'PROPRIETÁRIO')], verbose_name='tipo')),
                ('nascimento', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('credenciado', models.IntegerField(editable=False, null=True, verbose_name='credenciado')),
            ],
            options={
                'db_table': 'contato',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('credenciado', models.IntegerField(editable=False, null=True, verbose_name='credenciado')),
            ],
            options={
                'db_table': 'segmento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('credenciado', models.IntegerField(editable=False, null=True, verbose_name='credenciado')),
            ],
            options={
                'db_table': 'status',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, null=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fundacao',
            field=models.DateField(blank=True, null=True, verbose_name='fundação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.grupo', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ativo',
            field=models.BooleanField(default=True, null=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.segmento', verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.status', verbose_name='Status'),
        ),
    ]
