# Generated by Django 4.2.6 on 2024-01-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_contato_segmento_status_cliente_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='ativo',
            field=models.BooleanField(default=True, null=True, verbose_name='ativo'),
        ),
    ]
