# Generated by Django 4.2.6 on 2024-01-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_marca_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('credenciado', models.IntegerField(editable=False, null=True, verbose_name='credenciado')),
            ],
            options={
                'db_table': 'canal',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='canal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.canal', verbose_name='Canal'),
        ),
    ]
