# Generated by Django 4.2.6 on 2024-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_canal_cliente_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
    ]
