# Generated by Django 4.2.6 on 2024-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_vendedor_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='contato',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='contato',
            name='observacao',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observação'),
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='telefone'),
        ),
    ]
