# Generated by Django 4.2.6 on 2024-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_contato_email_contato_empresa_contato_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='telefone',
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone1',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='telefone móvel'),
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone2',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='telefone fixo'),
        ),
    ]
