# Generated by Django 4.2.6 on 2024-01-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_remove_contato_telefone_contato_telefone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('COMPRADOR', 'COMPRADOR'), ('GERENTE', 'GERENTE'), ('SOCIO', 'SÓCIO/ADMINISTRADOR'), ('PROPRIETARIO', 'PROPRIETÁRIO')], max_length=20, verbose_name='tipo'),
        ),
    ]
