# Generated by Django 4.2.6 on 2024-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_alter_contato_nome_alter_contato_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='tipo',
        ),
        migrations.AddField(
            model_name='contato',
            name='funcao',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='função'),
        ),
    ]
