# Generated by Django 4.2.6 on 2024-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_remove_contato_tipo_contato_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contatos',
            field=models.TextField(blank=True, default='', verbose_name='contatos'),
        ),
    ]
