# Generated by Django 4.2.6 on 2024-02-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_vendedor_agencia_vendedor_banco_vendedor_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='conta_dv',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='DV'),
        ),
    ]
