# Generated by Django 4.2.6 on 2024-03-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_vendedor_conta_dv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='cnpj')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=15, verbose_name='telefone')),
                ('endereco_cep', models.CharField(blank=True, default='', max_length=10, verbose_name='cep')),
                ('endereco_uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='', max_length=2, verbose_name='uf')),
                ('endereco_cidade', models.CharField(blank=True, default='', max_length=50, verbose_name='cidade')),
                ('endereco_logradouro', models.CharField(blank=True, default='', max_length=100, verbose_name='logradouro')),
                ('endereco_bairro', models.CharField(blank=True, default='', max_length=50, verbose_name='bairro')),
                ('endereco_numero', models.CharField(blank=True, default='', max_length=20, verbose_name='número')),
                ('marcas', models.TextField(blank=True, default='', verbose_name='marcas')),
                ('ativo', models.BooleanField(default=True, null=True, verbose_name='ativo')),
                ('credenciado', models.IntegerField(editable=False, null=True, verbose_name='credenciado')),
            ],
            options={
                'db_table': 'fabrica',
            },
        ),
    ]
