# Generated by Django 4.2.6 on 2024-03-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_fabrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrica',
            name='contato',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='contato'),
        ),
    ]
