# Generated by Django 4.2.6 on 2024-03-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_fabrica_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrica',
            name='cadastro',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='cadastro'),
        ),
    ]
