# Generated by Django 4.2.6 on 2024-03-31 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_fabrica_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('marcas', models.TextField(blank=True, default='', verbose_name='marcas')),
                ('cadastro', models.DateTimeField(blank=True, editable=False, verbose_name='cadastro')),
                ('credenciado', models.IntegerField(editable=False, null=True, verbose_name='credenciado')),
                ('semana', models.CharField(default='', max_length=100, verbose_name='semana')),
                ('prazo', models.SmallIntegerField(verbose_name='prazo')),
                ('parcela', models.SmallIntegerField(verbose_name='parcela')),
                ('desconto', models.FloatField(default=0, verbose_name='desconto')),
                ('qtde', models.SmallIntegerField(verbose_name='quantidade')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.cliente', verbose_name='Cliente')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.fabrica', verbose_name='Fabrica')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
