# Generated by Django 4.2 on 2024-06-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='parcela',
            field=models.SmallIntegerField(choices=[(1, '1 PARCELA'), (2, '2 PARCELAS'), (3, '3 PARCELAS')], default=3, verbose_name='parcela'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prazo',
            field=models.SmallIntegerField(default=45, verbose_name='prazo'),
        ),
    ]
