# Generated by Django 4.2 on 2024-06-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_alter_pedido_parcela_alter_pedido_prazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientemarca',
            name='marca',
        ),
        migrations.AddField(
            model_name='clientemarca',
            name='marca_id',
            field=models.IntegerField(null=True),
        ),
    ]
