# Generated by Django 4.2 on 2024-06-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0022_remove_clientemarca_marca_clientemarca_marca_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemarca',
            name='credenciado',
            field=models.IntegerField(null=True),
        ),
    ]
