# Generated by Django 4.2 on 2024-06-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0023_clientemarca_credenciado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_id', models.IntegerField(null=True)),
                ('credenciado', models.IntegerField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente', verbose_name='cliente')),
            ],
            options={
                'db_table': 'cliente_vendedor',
            },
        ),
    ]
