# Generated by Django 4.2 on 2024-08-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0024_clientevendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
