# Generated by Django 4.2 on 2024-08-19 03:44

import comercial.models.cliente
from django.db import migrations, models
import sisgeradm.storages


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0025_pedido_codigo_2_pedido_codigo_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_1',
            field=models.FileField(blank=True, null=True, storage=sisgeradm.storages.MediaStorage, upload_to=comercial.models.cliente.foto_1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_2',
            field=models.FileField(blank=True, null=True, storage=sisgeradm.storages.MediaStorage, upload_to=comercial.models.cliente.foto_2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_3',
            field=models.FileField(blank=True, null=True, storage=sisgeradm.storages.MediaStorage, upload_to=comercial.models.cliente.foto_3),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_4',
            field=models.FileField(blank=True, null=True, storage=sisgeradm.storages.MediaStorage, upload_to=comercial.models.cliente.foto_4),
        ),
    ]
