# Generated by Django 4.2 on 2025-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0026_cliente_foto_1_cliente_foto_2_cliente_foto_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_3',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
