# Generated by Django 4.2 on 2025-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0027_alter_pedido_codigo_2_alter_pedido_codigo_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fatura_mes',
            field=models.SmallIntegerField(choices=[(1, 'JANEIRO'), (2, 'FEVEREIRO'), (3, 'MARÇO'), (4, 'ABRIL'), (5, 'MAIO'), (6, 'JUNHO'), (7, 'JULHO'), (8, 'AGOSTO'), (9, 'SETEMBRO'), (10, 'OUTUBRO'), (11, 'NOVEMBRO'), (12, 'DEZEMBRO')], null=True, verbose_name='mês de faturamento'),
        ),
    ]
