# Generated by Django 4.2 on 2025-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0028_pedido_fatura_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='semana',
        ),
        migrations.AddField(
            model_name='pedido',
            name='semana_numero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='semana'),
        ),
    ]
