# Generated by Django 4.2 on 2025-03-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0029_remove_pedido_semana_pedido_semana_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='prazo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazos',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pedido',
            name='semana',
            field=models.SmallIntegerField(choices=[(1, '1ª SEMANA'), (2, '2ª SEMANA'), (3, '3ª SEMANA'), (4, '4ª SEMANA'), (5, '5ª SEMANA')], default=1, verbose_name='semana'),
        ),
    ]
