# Generated by Django 4.2 on 2025-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0030_remove_pedido_parcela_remove_pedido_prazo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='semana',
        ),
        migrations.AddField(
            model_name='pedido',
            name='embarque',
            field=models.SmallIntegerField(choices=[(1, '1ª SEMANA'), (2, '2ª SEMANA'), (3, '3ª SEMANA'), (4, '4ª SEMANA'), (5, '5ª SEMANA')], default=1, verbose_name='embarque'),
        ),
    ]
