# Generated by Django 4.2.6 on 2023-11-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='cnpj')),
                ('endereco_cep', models.CharField(blank=True, default='', max_length=10, verbose_name='cep')),
                ('endereco_uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='', max_length=2, verbose_name='uf')),
                ('endereco_cidade', models.CharField(blank=True, default='', max_length=50, verbose_name='cidade')),
                ('endereco_logradouro', models.CharField(blank=True, default='', max_length=100, verbose_name='logradouro')),
                ('endereco_numero', models.CharField(blank=True, default='', max_length=20, verbose_name='número')),
                ('endereco_bairro', models.CharField(blank=True, default='', max_length=50, verbose_name='bairro')),
                ('telefone_1', models.CharField(blank=True, default='', max_length=15, verbose_name='telefone 1')),
                ('telefone_2', models.CharField(blank=True, default='', max_length=15, verbose_name='telefone 2')),
            ],
            options={
                'db_table': 'credenciado',
            },
        ),
    ]
