# Generated by Django 4.2.6 on 2023-11-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciado',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='ativo'),
        ),
    ]
